version: "3.9"

services:
  python:
    container_name: thesis-analysis
    platform: linux/amd64
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/analysis
    ports:
      - 8888:8888
    command: jupyter lab --allow-root --no-browser --ip=0.0.0.0